name: build-e-push-imagem-docker
on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construir imagem
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/modelo_teste:latest .

      - name: Subir imagem
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/modelo_teste:latest